
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'About': typeof import("../components/About.vue")['default']
    'AjoutEleve': typeof import("../components/AjoutEleve.vue")['default']
    'AjouterEnseignant': typeof import("../components/AjouterEnseignant.vue")['default']
    'Bulletin': typeof import("../components/Bulletin.vue")['default']
    'CahierDeNote': typeof import("../components/CahierDeNote.vue")['default']
    'Commentaires': typeof import("../components/Commentaires.vue")['default']
    'Compte': typeof import("../components/Compte.vue")['default']
    'CreerClasse': typeof import("../components/CreerClasse.vue")['default']
    'CreerEnseignant': typeof import("../components/CreerEnseignant.vue")['default']
    'CreerMatiere': typeof import("../components/CreerMatiere.vue")['default']
    'CreerParent': typeof import("../components/CreerParent.vue")['default']
    'DashboardEleve': typeof import("../components/DashboardEleve.vue")['default']
    'DashboardEnseignant': typeof import("../components/DashboardEnseignant.vue")['default']
    'DashboardParent': typeof import("../components/DashboardParent.vue")['default']
    'EditerInfoEleve': typeof import("../components/EditerInfoEleve.vue")['default']
    'EditerInfoParent': typeof import("../components/EditerInfoParent.vue")['default']
    'EditerInfosEnseignant': typeof import("../components/EditerInfosEnseignant.vue")['default']
    'EditerNote': typeof import("../components/EditerNote.vue")['default']
    'GererClasse': typeof import("../components/GererClasse.vue")['default']
    'GererEleve': typeof import("../components/GererEleve.vue")['default']
    'GererEnseignant': typeof import("../components/GererEnseignant.vue")['default']
    'GererMatiere': typeof import("../components/GererMatiere.vue")['default']
    'GererParent': typeof import("../components/GererParent.vue")['default']
    'HomeAdmin': typeof import("../components/HomeAdmin.vue")['default']
    'HomeEleve': typeof import("../components/HomeEleve.vue")['default']
    'HomeEnseignant': typeof import("../components/HomeEnseignant.vue")['default']
    'HomeParent': typeof import("../components/HomeParent.vue")['default']
    'InfoEleve': typeof import("../components/InfoEleve.vue")['default']
    'InitierTrimestre': typeof import("../components/InitierTrimestre.vue")['default']
    'SupprimerClasse': typeof import("../components/SupprimerClasse.vue")['default']
    'SupprimerEleve': typeof import("../components/SupprimerEleve.vue")['default']
    'SupprimerEnseignant': typeof import("../components/SupprimerEnseignant.vue")['default']
    'SupprimerMatiere': typeof import("../components/SupprimerMatiere.vue")['default']
    'SupprimerParent': typeof import("../components/SupprimerParent.vue")['default']
    'VoirAvis': typeof import("../components/VoirAvis.vue")['default']
    'VoirEleves': typeof import("../components/VoirEleves.vue")['default']
    'VoirEnseignant': typeof import("../components/VoirEnseignant.vue")['default']
    'Notes': typeof import("../components/notes.vue")['default']
    'Trimestre': typeof import("../components/trimestre.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAbout': typeof import("../components/About.vue")['default']
    'LazyAjoutEleve': typeof import("../components/AjoutEleve.vue")['default']
    'LazyAjouterEnseignant': typeof import("../components/AjouterEnseignant.vue")['default']
    'LazyBulletin': typeof import("../components/Bulletin.vue")['default']
    'LazyCahierDeNote': typeof import("../components/CahierDeNote.vue")['default']
    'LazyCommentaires': typeof import("../components/Commentaires.vue")['default']
    'LazyCompte': typeof import("../components/Compte.vue")['default']
    'LazyCreerClasse': typeof import("../components/CreerClasse.vue")['default']
    'LazyCreerEnseignant': typeof import("../components/CreerEnseignant.vue")['default']
    'LazyCreerMatiere': typeof import("../components/CreerMatiere.vue")['default']
    'LazyCreerParent': typeof import("../components/CreerParent.vue")['default']
    'LazyDashboardEleve': typeof import("../components/DashboardEleve.vue")['default']
    'LazyDashboardEnseignant': typeof import("../components/DashboardEnseignant.vue")['default']
    'LazyDashboardParent': typeof import("../components/DashboardParent.vue")['default']
    'LazyEditerInfoEleve': typeof import("../components/EditerInfoEleve.vue")['default']
    'LazyEditerInfoParent': typeof import("../components/EditerInfoParent.vue")['default']
    'LazyEditerInfosEnseignant': typeof import("../components/EditerInfosEnseignant.vue")['default']
    'LazyEditerNote': typeof import("../components/EditerNote.vue")['default']
    'LazyGererClasse': typeof import("../components/GererClasse.vue")['default']
    'LazyGererEleve': typeof import("../components/GererEleve.vue")['default']
    'LazyGererEnseignant': typeof import("../components/GererEnseignant.vue")['default']
    'LazyGererMatiere': typeof import("../components/GererMatiere.vue")['default']
    'LazyGererParent': typeof import("../components/GererParent.vue")['default']
    'LazyHomeAdmin': typeof import("../components/HomeAdmin.vue")['default']
    'LazyHomeEleve': typeof import("../components/HomeEleve.vue")['default']
    'LazyHomeEnseignant': typeof import("../components/HomeEnseignant.vue")['default']
    'LazyHomeParent': typeof import("../components/HomeParent.vue")['default']
    'LazyInfoEleve': typeof import("../components/InfoEleve.vue")['default']
    'LazyInitierTrimestre': typeof import("../components/InitierTrimestre.vue")['default']
    'LazySupprimerClasse': typeof import("../components/SupprimerClasse.vue")['default']
    'LazySupprimerEleve': typeof import("../components/SupprimerEleve.vue")['default']
    'LazySupprimerEnseignant': typeof import("../components/SupprimerEnseignant.vue")['default']
    'LazySupprimerMatiere': typeof import("../components/SupprimerMatiere.vue")['default']
    'LazySupprimerParent': typeof import("../components/SupprimerParent.vue")['default']
    'LazyVoirAvis': typeof import("../components/VoirAvis.vue")['default']
    'LazyVoirEleves': typeof import("../components/VoirEleves.vue")['default']
    'LazyVoirEnseignant': typeof import("../components/VoirEnseignant.vue")['default']
    'LazyNotes': typeof import("../components/notes.vue")['default']
    'LazyTrimestre': typeof import("../components/trimestre.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const About: typeof import("../components/About.vue")['default']
export const AjoutEleve: typeof import("../components/AjoutEleve.vue")['default']
export const AjouterEnseignant: typeof import("../components/AjouterEnseignant.vue")['default']
export const Bulletin: typeof import("../components/Bulletin.vue")['default']
export const CahierDeNote: typeof import("../components/CahierDeNote.vue")['default']
export const Commentaires: typeof import("../components/Commentaires.vue")['default']
export const Compte: typeof import("../components/Compte.vue")['default']
export const CreerClasse: typeof import("../components/CreerClasse.vue")['default']
export const CreerEnseignant: typeof import("../components/CreerEnseignant.vue")['default']
export const CreerMatiere: typeof import("../components/CreerMatiere.vue")['default']
export const CreerParent: typeof import("../components/CreerParent.vue")['default']
export const DashboardEleve: typeof import("../components/DashboardEleve.vue")['default']
export const DashboardEnseignant: typeof import("../components/DashboardEnseignant.vue")['default']
export const DashboardParent: typeof import("../components/DashboardParent.vue")['default']
export const EditerInfoEleve: typeof import("../components/EditerInfoEleve.vue")['default']
export const EditerInfoParent: typeof import("../components/EditerInfoParent.vue")['default']
export const EditerInfosEnseignant: typeof import("../components/EditerInfosEnseignant.vue")['default']
export const EditerNote: typeof import("../components/EditerNote.vue")['default']
export const GererClasse: typeof import("../components/GererClasse.vue")['default']
export const GererEleve: typeof import("../components/GererEleve.vue")['default']
export const GererEnseignant: typeof import("../components/GererEnseignant.vue")['default']
export const GererMatiere: typeof import("../components/GererMatiere.vue")['default']
export const GererParent: typeof import("../components/GererParent.vue")['default']
export const HomeAdmin: typeof import("../components/HomeAdmin.vue")['default']
export const HomeEleve: typeof import("../components/HomeEleve.vue")['default']
export const HomeEnseignant: typeof import("../components/HomeEnseignant.vue")['default']
export const HomeParent: typeof import("../components/HomeParent.vue")['default']
export const InfoEleve: typeof import("../components/InfoEleve.vue")['default']
export const InitierTrimestre: typeof import("../components/InitierTrimestre.vue")['default']
export const SupprimerClasse: typeof import("../components/SupprimerClasse.vue")['default']
export const SupprimerEleve: typeof import("../components/SupprimerEleve.vue")['default']
export const SupprimerEnseignant: typeof import("../components/SupprimerEnseignant.vue")['default']
export const SupprimerMatiere: typeof import("../components/SupprimerMatiere.vue")['default']
export const SupprimerParent: typeof import("../components/SupprimerParent.vue")['default']
export const VoirAvis: typeof import("../components/VoirAvis.vue")['default']
export const VoirEleves: typeof import("../components/VoirEleves.vue")['default']
export const VoirEnseignant: typeof import("../components/VoirEnseignant.vue")['default']
export const Notes: typeof import("../components/notes.vue")['default']
export const Trimestre: typeof import("../components/trimestre.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAbout: typeof import("../components/About.vue")['default']
export const LazyAjoutEleve: typeof import("../components/AjoutEleve.vue")['default']
export const LazyAjouterEnseignant: typeof import("../components/AjouterEnseignant.vue")['default']
export const LazyBulletin: typeof import("../components/Bulletin.vue")['default']
export const LazyCahierDeNote: typeof import("../components/CahierDeNote.vue")['default']
export const LazyCommentaires: typeof import("../components/Commentaires.vue")['default']
export const LazyCompte: typeof import("../components/Compte.vue")['default']
export const LazyCreerClasse: typeof import("../components/CreerClasse.vue")['default']
export const LazyCreerEnseignant: typeof import("../components/CreerEnseignant.vue")['default']
export const LazyCreerMatiere: typeof import("../components/CreerMatiere.vue")['default']
export const LazyCreerParent: typeof import("../components/CreerParent.vue")['default']
export const LazyDashboardEleve: typeof import("../components/DashboardEleve.vue")['default']
export const LazyDashboardEnseignant: typeof import("../components/DashboardEnseignant.vue")['default']
export const LazyDashboardParent: typeof import("../components/DashboardParent.vue")['default']
export const LazyEditerInfoEleve: typeof import("../components/EditerInfoEleve.vue")['default']
export const LazyEditerInfoParent: typeof import("../components/EditerInfoParent.vue")['default']
export const LazyEditerInfosEnseignant: typeof import("../components/EditerInfosEnseignant.vue")['default']
export const LazyEditerNote: typeof import("../components/EditerNote.vue")['default']
export const LazyGererClasse: typeof import("../components/GererClasse.vue")['default']
export const LazyGererEleve: typeof import("../components/GererEleve.vue")['default']
export const LazyGererEnseignant: typeof import("../components/GererEnseignant.vue")['default']
export const LazyGererMatiere: typeof import("../components/GererMatiere.vue")['default']
export const LazyGererParent: typeof import("../components/GererParent.vue")['default']
export const LazyHomeAdmin: typeof import("../components/HomeAdmin.vue")['default']
export const LazyHomeEleve: typeof import("../components/HomeEleve.vue")['default']
export const LazyHomeEnseignant: typeof import("../components/HomeEnseignant.vue")['default']
export const LazyHomeParent: typeof import("../components/HomeParent.vue")['default']
export const LazyInfoEleve: typeof import("../components/InfoEleve.vue")['default']
export const LazyInitierTrimestre: typeof import("../components/InitierTrimestre.vue")['default']
export const LazySupprimerClasse: typeof import("../components/SupprimerClasse.vue")['default']
export const LazySupprimerEleve: typeof import("../components/SupprimerEleve.vue")['default']
export const LazySupprimerEnseignant: typeof import("../components/SupprimerEnseignant.vue")['default']
export const LazySupprimerMatiere: typeof import("../components/SupprimerMatiere.vue")['default']
export const LazySupprimerParent: typeof import("../components/SupprimerParent.vue")['default']
export const LazyVoirAvis: typeof import("../components/VoirAvis.vue")['default']
export const LazyVoirEleves: typeof import("../components/VoirEleves.vue")['default']
export const LazyVoirEnseignant: typeof import("../components/VoirEnseignant.vue")['default']
export const LazyNotes: typeof import("../components/notes.vue")['default']
export const LazyTrimestre: typeof import("../components/trimestre.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
